### ISSUE TITLE
Tons of issues

### ISSUE THREAD

**Issue by elamrouk** [supershdow/Project#3]
1. Sengen and Markov both break if you leave the field blank
2. One time I entered in Tom Sawyer for the Sentence Generator and it broke. It said "Key Error: 'of their lives at the present.'"
3. Entering a large number into the Sentence generator breaks it, with the error "range too large"
4. Entering a large number into the Caesar Cipher doesn't break it, but it never gives a result.
5. After signing up, I can't log in successfully
6. For Caesar Cipher, I can just enter in a symbol or # and it will return that symbol or # to me instead of asking me to at least provide a letter. I don't know if you would consider this an error.
7. Entering a number in the Sentence generator with a .0 (like 3.0) at  the end causes an error

**Comment by tanveerm176** [comment]
1. Sengen and Markov  both have been fixed now.
2. Tom Sawyer does that we don't know why
   .......

**Comment by supershdow** [comment]
1. Limits the number of sentences to 50
2. Limited the key size to 100
3. Fixed a problem with not adding line breaks
4. We do not intend to add that functionality

**Comment by supershdow** [comment]
1. Allowed user to input floats
